---
language: python
services: docker

env:
  global:
    - ROLE_NAME: redis
  matrix:
    - MOLECULE_DISTRO: rhel7

install:
  # Login to docker
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD" registry.redhat.io
  # Pull RHEL7 Docker Image
  - docker pull registry.access.redhat.com/rhel7
  # Install test dependencies.
  - pip install molecule docker

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-role-$ROLE_NAME nycrecords.$ROLE_NAME
  - cd nycrecords.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
